# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcessingCost', models.FloatField()),
                ('MemoryCost', models.FloatField()),
                ('StorageCost', models.FloatField()),
                ('BandwidthCost', models.FloatField()),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('AllocationPolicy', models.CharField(default='', max_length=100)),
                ('os', models.CharField(default='', max_length=100)),
                ('Hypervisor', models.CharField(default='', max_length=100)),
                ('SchedulingInterval', models.CharField(default=' ', max_length=100)),
                ('UpperThreshold', models.FloatField()),
                ('LowerThreshold', models.FloatField()),
                ('VMmigrations', models.CharField(default=' ', max_length=100)),
                ('MonitoringInterval', models.IntegerField()),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ram', models.FloatField()),
                ('Bandwidth', models.FloatField()),
                ('Storage', models.FloatField()),
                ('MaxPower', models.IntegerField()),
                ('StaticPower', models.IntegerField()),
                ('ProcessingElement', models.IntegerField()),
                ('MPS', models.CharField(default=' ', max_length=100)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.General')),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.AddField(
            model_name='costs',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.General'),
        ),
    ]
